from showyourwork.constants import USER
from pathlib import Path


def script_name(wildcards, input):
    """
    Returns the name of the figure script for the `figure` rule.

    Assumes the first python file in the `input` is the one that
    generates the script.

    """
    py_scripts = [file for file in input if file.endswith(".py")]
    return Path(py_scripts[0]).name


rule figure:
    params:
        script_name=script_name
    conda:
        str(USER / "environment.yml")
    shell:
        "cd {} ".format(str(USER / "figures")) + "&& python {params.script_name}"
