import snakemake_staging
from snakemake_staging.stages import NoOpStage

stage = NoOpStage("stage", config.get("restore", False))

rule a:
    output:
        stage("output/a.txt")
    run:
        raise ValueError("this should not be executed")

include:
    snakemake_staging.snakefile()
