version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-latest"

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: dirhtml
