[tool.towncrier]
package = "showyourwork"
directory = "docs/changes"
filename = "CHANGES.rst"
# let towncrier create proper links to the merged PR
issue_format = "`#{issue} <https://github.com/showyourwork/showyourwork/pulls/{issue}>`__"

[tool.towncrier.fragment.feature]
name = "New Features"
showcontent = true

[tool.towncrier.fragment.bugfix]
name = "Bug Fixes"
showcontent = true

[tool.towncrier.fragment.api]
name = "API Changes"
showcontent = true

[tool.towncrier.fragment.optimization]
name = "Refactoring and Optimization"
showcontent = true

[tool.towncrier.fragment.maintenance]
name = "Maintenance"
showcontent = true

[tool.towncrier.fragment.documentation]
name = "Documentation"
showcontent = true

[[tool.towncrier.section]]
name = ""
path = ""
