module syw:
    snakefile: "/Users/rluger/src/showyourwork/showyourwork-workflow/Snakefile"


rule fibonacci_data:
    output:
        "data/fibonacci.dat"
    shell:
        "curl https://zenodo.org/record/5187276/files/fibonacci.dat --output {output[0]}"


use rule figure from syw as fibonacci_figure with:
    input:
        "figures/fibonacci.py",
        "data/fibonacci.dat",
        "environment.yml"
    output:
        "figures/fibonacci.pdf"


use rule figure from syw as inline_figure with:
    input:
        "figures/inline.py",
        "environment.yml"
    output:
        "figures/inline.pdf"
