name: tests

on:
  push:
  workflow_dispatch:

jobs:
  showyourwork:
    runs-on: ubuntu-latest
    name: Build the article PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        with:
          run-tests: true
