name: Bug report
description: Template for bug reports
title: '[Bug]: '
labels:
  - ':bug: bug'
  - needs triage
body:
  - type: checkboxes
    id: pre
    attributes:
      label: Preliminary checks
      description: >-
        Please, make sure you go through the following sections of our
        documentation before you actually submit a bug report!
      options:
        - label: https://show-your.work/en/latest/known_issues/
          required: true
        - label: https://show-your.work/en/latest/faqs/
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened / did you expect to happen?
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Please, provide steps to reproduce the problem in a minimal way.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Paste here any error logs
  - type: textarea
    id: version
    attributes:
      label: Setup information
      description: What version of our software and its dependencies are you running?
      value: |
        Run this code snippet in the same environment where the bug arises:

        ```python
        import platform; print(f"Platform: {platform.platform()}")
        import platform; print(f"Python: {platform.python_version()}")
        import showyourwork; print(f"showyourwork: {showyourwork.__version__}")
        ```