import yaml
from helpers import (
    ShowyourworkRepositoryActions,
    TemporaryShowyourworkRepository,
)


class TestDependencyKeyTypo(
    TemporaryShowyourworkRepository, ShowyourworkRepositoryActions
):
    """
    Test that the build fails when a dependency key does not match any
    known figure script or the manuscript TeX file (issue #242).
    """

    # No need to test this on CI
    local_build_only = True

    def customize(self):
        # Add a working figure script
        self.add_figure_script()

        # Add a figure environment to the tex file
        self.add_figure_environment()

        # Add a dependency with a typo in the script name key
        config_path = self.cwd / "showyourwork.yml"
        with open(config_path) as f:
            config = yaml.safe_load(f)

        config["dependencies"] = {
            "src/scripts/test_figur.py": [  # typo: "figur" instead of "figure"
                "src/data/some_data.dat",
            ],
        }

        with open(config_path, "w") as f:
            yaml.dump(config, f, default_flow_style=False)

    def build_local(self):
        try:
            super().build_local()
        except Exception as e:
            if "test_figur.py" not in str(e) or (
                "does not correspond to any figure script" not in str(e)
            ):
                raise Exception(f"Build failed with unexpected error message: {str(e)}")
        else:
            raise Exception(
                "Expected build to fail due to dependency key typo, but it succeeded."
            )


class TestDependencyValueNotGenerated(
    TemporaryShowyourworkRepository, ShowyourworkRepositoryActions
):
    """
    Test that the build fails when a dependency value (file) is expected
    to be generated by the workflow but is not an output of any Snakemake rule.

    Since dependency values become direct inputs to figure rules, Snakemake
    itself will raise a MissingInputException. We verify the user gets a
    clear error mentioning the missing file.
    """

    # No need to test this on CI
    local_build_only = True

    def customize(self):
        # Add a working figure
        self.add_figure_script()
        self.add_figure_environment()

        # Add a dependency that refers to a non-existent generated file
        config_path = self.cwd / "showyourwork.yml"
        with open(config_path) as f:
            config = yaml.safe_load(f)

        config["dependencies"] = {
            "src/scripts/test_figure.py": [
                "src/data/nonexistent_data.npz",  # no rule generates this
            ],
        }

        with open(config_path, "w") as f:
            yaml.dump(config, f, default_flow_style=False)

    def build_local(self):
        try:
            super().build_local()
        except Exception as e:
            if "nonexistent_data.npz" not in str(e):
                raise Exception(
                    f"Build failed but error does not mention the missing "
                    f"dependency file: {str(e)}"
                )
        else:
            raise Exception(
                "Expected build to fail due to unresolved dependency value, "
                "but it succeeded."
            )


class TestDependencyValueStaticMissing(
    TemporaryShowyourworkRepository, ShowyourworkRepositoryActions
):
    """
    Test that the build fails when a dependency value under src/tex/
    (a static location, outside figures/ and output/) does not exist on disk.

    Since dependency values become direct inputs to figure rules, Snakemake
    itself will raise a MissingInputException. We verify the user gets a
    clear error mentioning the missing file.
    """

    # No need to test this on CI
    local_build_only = True

    def customize(self):
        # Add a working figure
        self.add_figure_script()
        self.add_figure_environment()

        # Add a dependency that refers to a non-existent static file under src/tex
        config_path = self.cwd / "showyourwork.yml"
        with open(config_path) as f:
            config = yaml.safe_load(f)

        config["dependencies"] = {
            "src/scripts/test_figure.py": [
                "src/tex/missing_bibliography.bib",  # doesn't exist
            ],
        }

        with open(config_path, "w") as f:
            yaml.dump(config, f, default_flow_style=False)

    def build_local(self):
        try:
            super().build_local()
        except Exception as e:
            if "missing_bibliography.bib" not in str(e):
                raise Exception(
                    f"Build failed but error does not mention the missing "
                    f"dependency file: {str(e)}"
                )
        else:
            raise Exception(
                "Expected build to fail due to missing static dependency, "
                "but it succeeded."
            )
