import snakemake_staging
from snakemake_staging.stages import NoOpStage

stage = NoOpStage("stage", config.get("restore", False))

rule a:
    output:
        stage("output/a.txt")
    shell:
        """
        mkdir -p output
        echo "test" > {output}
        """

include:
    snakemake_staging.snakefile()
