name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    permissions: write-all
    concurrency: "{% raw %}showyourwork-${{ github.ref }}{% endraw %}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build the article PDF
        id: build
        uses: showyourwork/showyourwork-action@{{ cookiecutter.action_version or 'v1' }}
        {%- if cookiecutter.action_spec %}
        with:
          showyourwork-spec: {{ cookiecutter.action_spec }}{% endif %}
        env:
          SANDBOX_TOKEN: "{% raw %}${{ secrets.SANDBOX_TOKEN }}{% endraw %}"
          OVERLEAF_TOKEN: "{% raw %}${{ secrets.OVERLEAF_TOKEN }}{% endraw %}"
