import subprocess
from pathlib import Path
import shutil
import json


# Params defined in `../rules/figure.smk`
script_name = snakemake.params["script_name"]
this_figure = snakemake.output[0]
this_figure_name = Path(this_figure).name
FIGURES = snakemake.params["FIGURES"]
TEMP = snakemake.params["TEMP"]


# Get the names of all _other_ figures generated by the
# current script. This is used for caching.
try:
    with open(TEMP / "scripts.json", "r") as f:
        scripts = json.load(f)
    for entry in scripts["figures"].values():
        if Path(entry["script"]).name == script_name:
            other_figures = [
                Path(file).name for file in entry["files"] if file != this_figure
            ]
            break
    else:
        other_figures = []
except FileNotFoundError:
    # If `scripts.json` doesn't exist for some reason,
    # fail silently without caching
    other_figures = []

if len(other_figures):

    # This script has multiple outputs.
    if (TEMP / this_figure_name).exists():

        # The figure exists in the cache; copy it over
        shutil.move(str(TEMP / this_figure_name), str(FIGURES / this_figure_name))

    else:

        # We need to run the script
        subprocess.check_call(["python", script_name], cwd=FIGURES)

        # Cache the other files
        for figure in other_figures:

            shutil.move(str(FIGURES / figure), str(TEMP / figure))

else:

    # This script has only one output, so no need for caching
    subprocess.check_call(["python", script_name], cwd=FIGURES)
