from showyourwork import paths

include: paths.package_data("showyourwork.plugins.tex", "workflow", "rules", "common.smk")
include: paths.package_data("showyourwork.plugins.tex", "workflow", "rules", "dependencies.smk")
include: paths.package_data("showyourwork.plugins.tex", "workflow", "rules", "build.smk")
