name: local tests

on:
  push:
    branches:
      - main
      - staging*
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"
        platform:
          - ubuntu-latest
          - windows-latest
        # include:
        #   - platform: macos-latest
        #     python: "3.9"
    runs-on: ${{ matrix.platform }}
    name: Run local integration tests
    env:
      ACTION_SHELL: ${{ runner.os == 'Windows' && 'powershell' || 'bash -l {0}' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python and mamba
        uses: mamba-org/setup-micromamba@v3
        with:
          micromamba-version: '2.6.0-0' # see https://github.com/mamba-org/setup-micromamba/issues/306
          environment-name: test-env
          init-shell: >-
            bash
            powershell
          create-args: >-
            python=${{ matrix.python }}
            conda

      - name: Set channel priority
        shell: ${{ env.ACTION_SHELL }}
        run: |
          conda config --set channel_priority strict

      - name: Install showyourwork
        shell: ${{ env.ACTION_SHELL }}
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[tests]"

      - name: Run local integration tests
        shell: ${{ env.ACTION_SHELL }}
        run: python -m pytest tests/integration
