name: unit tests

on:
  push:
    branches:
      - main
      - staging*
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"
        platform:
          - ubuntu-latest
          - windows-latest
        # include:
        #   - platform: macos-latest
        #     python: "3.9"
    runs-on: ${{ matrix.platform }}
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python and mamba
        uses: mamba-org/setup-micromamba@v3
        with:
          micromamba-version: '2.6.2-1' # see https://github.com/mamba-org/setup-micromamba/issues/306
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python }}
            mamba

      - name: Install showyourwork
        shell: bash
        run: |
          micromamba run -n test-env python -m pip install -U pip --break-system-packages
          micromamba run -n test-env python -m pip install -e ".[tests]" --break-system-packages

      - name: Run tests
        shell: bash
        run: |
          micromamba run -n test-env python -m pytest tests/unit 
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
