"""
The Snakefile for the main article build step.

"""
from showyourwork import paths, exceptions, overleaf
from showyourwork.patches import patch_snakemake_wait_for_files, patch_snakemake_logging, patch_snakemake_missing_input_leniency
from showyourwork.config import parse_config, get_run_type
from showyourwork.logging import get_logger
from showyourwork.userrules import process_user_rules
from showyourwork.git import get_repo_branch
import snakemake
import sys
import yaml


# Working directory is the top level of the user repo
workdir: paths.user().repo.as_posix()


# What kind of run is this? (clean, build, etc.)
run_type = get_run_type()


# The configfile is autogenerated by the `prep.smk` workflow
if (paths.user().temp / "config.json").exists():


    # Load the autogenerated config
    configfile: (paths.user().temp / "config.json").as_posix()


    # Workflow report template
    report: "report/workflow.rst"


    # Remove old flags
    for file in paths.user().flags.glob("*"):
        file.unlink()


    # Set up custom logging for Snakemake
    patch_snakemake_logging()


    # Parse the config file
    parse_config()


    # Hack to make the pdf generation the default rule
    rule syw__main:
        input:
            config["ms_pdf"],
            (config["ms_name"] + ".synctex.gz" if config["synctex"] else [])

    # Wrap other top-level rules to ensure tempfiles are properly
    # deleted; these are the rules we actually call from the Makefile
    rule syw__arxiv_entrypoint:
        input:
            "arxiv.tar.gz"


    # Keep render_dag env python aligned with current interpreter to avoid cross-version pickle issues
    base_render_dag_yml = paths.showyourwork().envs / "render_dag.yml"
    with open(base_render_dag_yml, "r") as f:
        render_dag_config = yaml.safe_load(f)
    python_version = f"{sys.version_info.major}.{sys.version_info.minor}"
    new_deps = []
    for dep in render_dag_config["dependencies"]:
        if isinstance(dep, str) and dep.startswith("python"):
            new_deps.append(f"python={python_version}")
        else:
            new_deps.append(dep)
    render_dag_config["dependencies"] = new_deps
    render_dag_env = paths.user().temp / "render_dag.dynamic.yml"
    render_dag_env.parent.mkdir(parents=True, exist_ok=True)
    with open(render_dag_env, "w") as f:
        yaml.dump(render_dag_config, f, default_flow_style=False)
    render_dag_env = render_dag_env.as_posix()


    # Include all other rules
    include: "rules/common.smk"
    include: "rules/dag.smk"
    include: "rules/arxiv.smk"
    include: "rules/compile.smk"
    include: "rules/zenodo.smk"
    include: "rules/figure.smk"
    include: "rules/render_dag.smk"

    # Resolve ambiguities in rule order
    ruleorder: syw__compile > syw__arxiv


    # Include custom rules defined by the user
    include: (paths.user().repo / "Snakefile").as_posix()
    process_user_rules()


    # Hack to display a custom message when a figure output is missing
    patch_snakemake_wait_for_files()


    # Snakemake workflows complete successfully if there's no rule to generate
    # a given file but it is present on disk. This is bad for third-party
    # reproducibility, so here we hack it to require all inputs to be present.
    if config["require_inputs"]:
        patch_snakemake_missing_input_leniency()


else:


    if workflow.output_settings.dryrun:
        get_logger().warn(
            "--dry-run is only partially supported with showyourwork."
            "The output will not be representative of what would actually run."
        )

    if run_type != "clean" and not workflow.output_settings.dryrun:
        raise exceptions.MissingConfigFile()


onsuccess:


    # Overleaf sync: push changes
    if run_type == "build" and get_repo_branch() == "main":
        overleaf.push_files(config["overleaf"]["push"], config["overleaf"]["id"])


    # We're done
    get_logger().info("Done!")
